@base = http://localhost:3000/api
@type = application/json
@createdAt = {{$datetime iso8601}}

###

GET {{base}}/task

###

GET {{base}}/project/1

###

GET http://localhost:3000/api/project/1
content-type: application/json

###

GET http://localhost:3000/api/task

###

PUT {{base}}/task/edit
content-type: application/json

{
	"id": 1,
	"title": "hello",
	"body": "this is the body",
	"columnId": 100,
	"index": 100
}